# Generated by Django 2.1.7 on 2019-02-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Waiting_person',
            new_name='Customer',
        ),
    ]
