# Generated by Django 2.1.7 on 2019-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0002_auto_20190222_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='waiting_number',
            field=models.IntegerField(default=0),
        ),
    ]
