# Generated by Django 2.1.7 on 2019-02-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0003_customer_waiting_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='waiting_number',
        ),
    ]
