# Generated by Django 2.1.7 on 2019-02-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0006_remove_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_people', models.IntegerField(default=0)),
            ],
        ),
    ]
