# Generated by Django 2.1.7 on 2019-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0007_waitinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='waiting_number',
            field=models.IntegerField(default=0),
        ),
    ]
