# Generated by Django 2.1.7 on 2019-02-22 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0008_waitinglist_waiting_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='waiting_number',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tigtag.Customer'),
            preserve_default=False,
        ),
    ]
