# Generated by Django 2.1.7 on 2019-02-22 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0009_auto_20190223_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitinglist',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
