# Generated by Django 2.1.7 on 2019-02-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0010_auto_20190223_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='waiting_number',
            field=models.IntegerField(default=0),
        ),
    ]
