# Generated by Django 2.1.7 on 2019-02-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0012_auto_20190223_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='phone_number',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
