# Generated by Django 2.1.7 on 2019-02-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0015_remove_waitinglist_waiting_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='customer',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
