# Generated by Django 2.1.7 on 2019-02-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0016_auto_20190223_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='waiting_number',
            field=models.IntegerField(db_index=True),
        ),
    ]
