# Generated by Django 2.1.7 on 2019-02-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0017_auto_20190223_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='customer_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tigtag.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='customer',
            name='waiting_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
