# Generated by Django 2.1.7 on 2019-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0018_auto_20190223_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
    ]
