# Generated by Django 2.1.7 on 2019-02-23 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigtag', '0019_auto_20190223_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tigtag.Customer'),
        ),
    ]
